### PR TITLE
refine base elements

### PR DESCRIPTION
**Pull request by jzhang300**
* make base elements not reliant on `base--*` class name
* have header and p tags use rems instead of ems

### CODE REVIEW

**Comment by jzhang300** [comment]
I need to test this on an html page before merging.

**Comment by germanattanasio** [comment]
I think this is a breaking change. Probably a major release. I'm a little bit worried be cafeful!

**Comment by nfriedly** [comment]
Since we're still on major version 0, a "minor" bump should be fine here. Anything targeting `~0.5.4` or `^0.5.4` (the current release), will not install a `0.6.0` release.

**Comment by jzhang300** [comment]
Yeah I'm a bit worried about this as well...

Not really sure how to handle such a huge breaking change

**Comment by nfriedly** [comment]
What I was saying is that calling this 0.6.0 and putting a note in the README explaining the changes should be enough. 

Nothing will break, it'll just stay on the older versions of the lib (which will continue to be available from npm.)

Also, pre v1.0 you're *allowed* to break things. That's the point.

**Comment by germanattanasio** [comment]
Let's merge it then!!!!!

**Comment by germanattanasio** [comment]
@jzhang300 let me know when the PR is ready for review

**Comment by jzhang300** [comment]
@germanattanasio ok it's ready.  I just tried using the styles without the classnames and it seemed to work just fine.

**Pull request merged**
